### ISSUE TITLE
HTML/CSS opmerkingen

### ISSUE THREAD

**Issue by KaanKalmi** [smolgeorgie/the-startup-responsive-interactieve-website#2]
### HTML
- HTML Validatie:
![image](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144000125/9f4f1c8f-2c85-4d91-9b3d-b0429a678e1c)
In principe niet erg maar is er geen ander element naast `<article>` dat je kan gebruiken voor de container?
- Leuk gebruik gemaakt van `aria-hidden=true` want een screenreader hoeft het natuurlijk niet op te lezen!

### CSS

- Waarom gebruik je niet vaker CSS nesting? [Hier kan je meer over CSS Nesting lezen](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting)
![image](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144000125/9dcc78a1-a573-42a0-90a3-c7a80616f831)

**edit**
- Ik zie dat je de property size hebt gebruikt: 
![image](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144000125/8181be02-09ea-4ff5-ac20-9df591ffe3f5)
Maar de property size kan alleen bij een `@page` wat jij neit hebt gebruikt, bedoel je misschien `resize`? 
[Kijk hier voor meer info over de property `size`](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size)

**Comment by smolgeorgie** [comment]
Nesting complete: 

```css
.object-primary__calculator {
    display: flex;
    flex-direction: row;
    align-items: center;
    color: var(--link-color);
    font-size: var(--font-size-paragraph);
    cursor: pointer;
    margin: 1em 0 0 .5em;
    font-size: 15px;
    border-bottom: 1px lightgray solid;

    & figure svg {
        height: 1.5em;
        width: 1.5em;
        fill: grey;
    }

    & a {
        text-decoration: none;
        color: var(--link-color);
        font-weight: var(--link-weight);
    }
}
```
